apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
type: Opaque
data:
  MAIL_USERNAME: aWR1MjAxODE1MDI1QGdtYWlsLmNvbQ==
  MAIL_PASSWORD: a2h4eHpxanBscXZoY3J0Zw==
  MAIL_FROM: aWR1MjAxODE1MDI1QGdtYWlsLmNvbQ==
